# Generated by Django 4.2.4 on 2023-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
